baseURL = "http://localhost/findingaids/"
languageCode = "en-us"
title = "Sample set 2 -- EAD source files v3.1 (https://github.com/NYULibraries/dlts-finding-aids-ead-sample-set-2/tag/v3.1) "
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]



[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["overview", "contents" ]

[outputFormats]
  [outputFormats.overview]
    name = "Overview"
    baseName = "index"
    isPlainText = false
    isHTML = true
    mediaType = "text/html"
    notAlternative = true
    permalinkable = true
  [outputFormats.contents]
    name = "Contents"
    baseName = "contents"
    isPlainText = false
    isHTML = true
    mediaType = "text/html"
    notAlternative = false
    permalinkable = true
  [outputFormats.alldata]
    name = "Alldata"
    baseName = "alldata"
    isPlainText = false
    isHTML = true
    mediaType = "text/html"
    notAlternative = false
    permalinkable = true



[module]
  [[module.imports]]
    path = "github.com/NYULibraries/findingaids-hugo-theme"
  